/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                'bg-app': 'var(--bg-app)',
                'bg-panel': 'var(--bg-panel)',
                'bg-card': 'var(--bg-card)',
                'bg-hover': 'var(--bg-hover)',
                'border-subtle': 'var(--border-subtle)',
                'border-active': 'var(--border-active)',
                'primary': 'var(--text-primary)',
                'secondary': 'var(--text-secondary)',
                'tertiary': 'var(--text-tertiary)',
                'accent-primary': 'var(--accent-primary)',
                'accent-hover': 'var(--accent-hover)',
                'accent-subtle': 'var(--accent-subtle)',

                'status-backlog': 'var(--status-backlog)',
                'status-todo': 'var(--status-todo)',
                'status-inprogress': 'var(--status-inprogress)',
                'status-review': 'var(--status-review)',
                'status-done': 'var(--status-done)',
            },
            borderRadius: {
                'xs': '4px',
                'sm': '8px',
                'md': '12px',
                'lg': '16px',
                'xl': '28px',
            },
            fontSize: {
                'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
                'display-md': ['45px', { lineHeight: '52px' }],
                'display-sm': ['36px', { lineHeight: '44px' }],
                'headline-lg': ['32px', { lineHeight: '40px' }],
                'headline-md': ['28px', { lineHeight: '36px' }],
                'headline-sm': ['24px', { lineHeight: '32px' }],
                'title-lg': ['22px', { lineHeight: '28px' }],
                'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
                'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
                'body-lg': ['16px', { lineHeight: '24px' }],
                'body-md': ['14px', { lineHeight: '20px' }],
                'body-sm': ['12px', { lineHeight: '16px' }],
                'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'label-sm': ['11px', { lineHeight: '16px' }],
            },
            boxShadow: {
                'elevation-1': '0 1px 2px rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
                'elevation-2': '0 1px 2px rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
                'elevation-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px rgba(0,0,0,0.3)',
                'elevation-4': '0 6px 10px 4px rgba(0,0,0,0.15), 0 2px 3px rgba(0,0,0,0.3)',
            },
        },
    },
    plugins: [],
}
