/**
 * AP-153: project creation wizard.
 *
 * Four steps: basics → attachments → initial tasks → agents.
 *
 * The wizard owns every value that used to be auto-generated by code —
 * specifically, the body of the kickoff task and the choice of which
 * agents are on the project. Per the prompts-as-config principle:
 * prompt-shaped content (task descriptions, agent personas) is collected
 * here from the user, never hard-coded.
 *
 * Submission flow:
 *   1. POST /api/projects { name, description, initial_tasks, members }
 *      → backend creates the project + tasks + memberships in one shot,
 *        and explicitly skips the legacy auto-seed.
 *   2. For each staged file: POST /api/projects/{id}/attachments
 *   3. Navigate to the board.
 */

import React, { useState, useRef, useEffect, useCallback } from 'react';
import { api } from '../api';
import { ROUTES } from '../routes';
import { useNavigate } from 'react-router-dom';
import {
    Briefcase, X, Upload, FileText, Trash2, Plus, Check,
    ChevronLeft, ChevronRight,
} from 'lucide-react';

const PROJECT_CATEGORIES = [
    'Software Engineering', 'Product Management', 'Marketing',
    'Design', 'Operations', 'Research', 'Other',
];

const PRIORITIES = ['low', 'medium', 'high', 'critical'];

const STEPS = [
    { key: 'basics',      label: 'Basics' },
    { key: 'attachments', label: 'Attachments' },
    { key: 'tasks',       label: 'Initial tasks' },
    { key: 'agents',      label: 'Agents' },
];

function formatSize(bytes) {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}


export function CreateProjectWizard({ onClose, onSuccess }) {
    const [step, setStep] = useState(0);
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState(null);

    // Step 1 — basics
    const [name, setName] = useState('');
    const [category, setCategory] = useState('');
    const [description, setDescription] = useState('');

    // Step 2 — attachments (uploaded after project create)
    const [files, setFiles] = useState([]);

    // Step 3 — initial tasks. Pre-populated with a single "Plan this
    // project" row carrying a terse starter prompt that's visible in the
    // form. This is a UI default, not a runtime override — the user sees
    // it on screen and can edit, expand, or delete before submit. By
    // the time it lands on Task.description, the user has authored it
    // (or accepted it). That's the "standard route" the prompts-as-config
    // principle calls for.
    const [tasks, setTasks] = useState([
        {
            title: 'Plan this project',
            description:
                'Read the project description and any uploaded files (they live on the project, ' +
                'not this task). Output a one-page plan as a `report` artifact and create 3–8 ' +
                'concrete child tasks for the work, including CI/CD setup if appropriate.',
            assignee: 'Conductor',
            priority: 'high',
        },
    ]);

    // Step 4 — available agents to attach
    const [availableAgents, setAvailableAgents] = useState([]);
    const [selectedAgents, setSelectedAgents] = useState(new Set(['Conductor']));

    const navigate = useNavigate();
    const modalRef = useRef(null);

    useEffect(() => {
        // Pull agents (role=bot) so step 4 lists what's available to
        // attach. Conductor is always at the top, pre-checked.
        api.getProfiles('bot').then((rows) => {
            setAvailableAgents(Array.isArray(rows) ? rows : []);
        }).catch(() => setAvailableAgents([]));
    }, []);

    const canAdvance = (s) => {
        if (s === 0) return name.trim().length > 0;
        return true;
    };

    const next = () => { if (canAdvance(step)) setStep((s) => Math.min(s + 1, STEPS.length - 1)); };
    const back = () => setStep((s) => Math.max(s - 1, 0));

    const buildDescription = () => {
        const body = description.trim();
        if (category) return `**Category:** ${category}\n\n${body}`;
        return body;
    };

    const handleSubmit = async () => {
        setSubmitting(true);
        setError(null);
        try {
            const validTasks = tasks
                .filter((t) => t.title.trim())
                .map((t) => ({
                    title: t.title.trim(),
                    description: t.description,
                    assignee: t.assignee || '',
                    priority: t.priority || 'medium',
                    status: 'todo',
                }));
            const members = Array.from(selectedAgents);
            const project = await api.createProject({
                name: name.trim(),
                description: buildDescription(),
                initial_tasks: validTasks,
                members,
            });

            const folderFiles = files.filter((f) => f.relativePath || f.webkitRelativePath);
            const looseFiles = files.filter((f) => !(f.relativePath || f.webkitRelativePath));
            try {
                if (folderFiles.length) await api.uploadProjectFolder(project.id, folderFiles);
            } catch (e) { console.error('folder upload failed:', e); }
            for (const file of looseFiles) {
                try { await api.uploadProjectAttachment(project.id, file); }
                catch (e) { console.error('attachment upload failed:', e); }
            }

            onSuccess?.();
            navigate(ROUTES.STUDIO_BOARD(project.id));
            onClose();
        } catch (e) {
            setError(e.message || 'Project creation failed');
        } finally {
            setSubmitting(false);
        }
    };

    const handleBackdropClick = (e) => {
        if (modalRef.current && !modalRef.current.contains(e.target)) onClose();
    };

    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm animate-fade-in"
            onClick={handleBackdropClick}
        >
            <div
                ref={modalRef}
                className="w-full max-w-2xl rounded-xl shadow-2xl overflow-hidden flex flex-col"
                style={{ backgroundColor: 'var(--bg-card)', border: '1px solid var(--border-subtle)', maxHeight: '85vh' }}
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div className="px-6 py-4 flex items-center gap-3 flex-shrink-0"
                     style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                    <div className="w-10 h-10 rounded-lg flex items-center justify-center shadow-lg flex-shrink-0"
                         style={{ backgroundColor: 'var(--accent-primary)' }}>
                        <Briefcase className="w-5 h-5 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                        <h3 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>
                            New project — {STEPS[step].label}
                        </h3>
                        <StepIndicator step={step} />
                    </div>
                    <button onClick={onClose}
                            className="p-1.5 rounded-xl transition-colors hover:bg-bg-hover"
                            style={{ color: 'var(--text-tertiary)' }}>
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Step body */}
                <div className="p-6 overflow-y-auto custom-scrollbar flex-1">
                    {step === 0 && (
                        <BasicsStep
                            name={name} setName={setName}
                            category={category} setCategory={setCategory}
                            description={description} setDescription={setDescription}
                        />
                    )}
                    {step === 1 && (
                        <AttachmentsStep files={files} setFiles={setFiles} />
                    )}
                    {step === 2 && (
                        <InitialTasksStep tasks={tasks} setTasks={setTasks} />
                    )}
                    {step === 3 && (
                        <AgentsStep
                            available={availableAgents}
                            selected={selectedAgents}
                            setSelected={setSelectedAgents}
                        />
                    )}
                </div>

                {/* Footer */}
                <div className="px-6 py-4 flex items-center justify-between flex-shrink-0"
                     style={{ borderTop: '1px solid var(--border-subtle)' }}>
                    <div className="text-xs" style={{ color: '#ef4444' }}>{error || ''}</div>
                    <div className="flex gap-2">
                        {step > 0 && (
                            <button type="button" onClick={back} className="btn btn-ghost flex items-center gap-1">
                                <ChevronLeft className="w-4 h-4" /> Back
                            </button>
                        )}
                        {step < STEPS.length - 1 ? (
                            <button type="button" onClick={next} disabled={!canAdvance(step)}
                                    className="btn btn-primary flex items-center gap-1">
                                Next <ChevronRight className="w-4 h-4" />
                            </button>
                        ) : (
                            <button type="button" onClick={handleSubmit} disabled={submitting || !name.trim()}
                                    className="btn btn-primary flex items-center gap-1">
                                <Check className="w-4 h-4" /> {submitting ? 'Creating…' : 'Create project'}
                            </button>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}


function StepIndicator({ step }) {
    return (
        <div className="flex items-center gap-1.5 mt-1">
            {STEPS.map((s, i) => (
                <React.Fragment key={s.key}>
                    <div className="rounded-full transition-colors"
                         style={{
                             width: i === step ? 18 : 6, height: 6,
                             backgroundColor: i <= step ? 'var(--accent-primary)' : 'var(--border-subtle)',
                         }}
                    />
                </React.Fragment>
            ))}
            <span className="text-[10px] ml-2" style={{ color: 'var(--text-tertiary)' }}>
                Step {step + 1} of {STEPS.length}
            </span>
        </div>
    );
}


function BasicsStep({ name, setName, category, setCategory, description, setDescription }) {
    return (
        <div className="space-y-4">
            <div>
                <Label required>Project name</Label>
                <input
                    type="text" value={name} onChange={(e) => setName(e.target.value)}
                    className="input" placeholder="e.g. LeadCore" autoFocus
                />
            </div>
            <div>
                <Label>Category</Label>
                <div className="flex flex-wrap gap-2">
                    {PROJECT_CATEGORIES.map((c) => (
                        <button key={c} type="button"
                                onClick={() => setCategory(c === category ? '' : c)}
                                className="px-3 py-1.5 rounded-full text-xs font-medium transition-all border"
                                style={category === c ? {
                                    borderColor: 'var(--accent-primary)',
                                    color: 'var(--accent-primary)',
                                    backgroundColor: 'var(--accent-subtle)',
                                } : {
                                    borderColor: 'var(--border-subtle)',
                                    color: 'var(--text-secondary)',
                                    backgroundColor: 'transparent',
                                }}>
                            {c}
                        </button>
                    ))}
                </div>
            </div>
            <div>
                <Label>Description</Label>
                <textarea value={description} onChange={(e) => setDescription(e.target.value)}
                          className="input resize-none h-24"
                          placeholder="What is this project about?" />
            </div>
        </div>
    );
}


// Drag-drop folder expansion: a single drop accepts loose files OR whole
// folders (the file picker can't do both in one OS dialog, but drag can).
// webkitGetAsEntry must be read synchronously during the drop event, so we
// collect entries first, then walk them. Files inside a folder get a
// `relativePath` so structure is preserved on upload.
async function readEntry(entry, prefix, out) {
    if (entry.isFile) {
        await new Promise((resolve) => entry.file((file) => {
            if (prefix) file.relativePath = prefix + file.name;
            out.push(file);
            resolve();
        }, resolve));
    } else if (entry.isDirectory) {
        const reader = entry.createReader();
        await new Promise((resolve) => {
            const next = () => reader.readEntries(async (batch) => {
                if (!batch.length) return resolve();
                for (const e of batch) await readEntry(e, prefix + entry.name + '/', out);
                next();
            }, resolve);
            next();
        });
    }
}

async function filesFromDrop(dataTransfer) {
    const entries = Array.from(dataTransfer.items || [])
        .map((it) => it.webkitGetAsEntry?.())
        .filter(Boolean);
    if (!entries.length) return Array.from(dataTransfer.files || []);
    const out = [];
    for (const entry of entries) await readEntry(entry, '', out);
    return out;
}

function AttachmentsStep({ files, setFiles }) {
    const fileInputRef = useRef(null);
    const folderInputRef = useRef(null);
    const [drag, setDrag] = useState(false);

    const addFiles = useCallback((list) => {
        const arr = Array.from(list || []);
        const key = (f) => (f.relativePath || f.webkitRelativePath || f.name) + f.size;
        setFiles((prev) => {
            const seen = new Set(prev.map(key));
            return [...prev, ...arr.filter((f) => !seen.has(key(f)))];
        });
    }, [setFiles]);

    const remove = (i) => setFiles((prev) => prev.filter((_, idx) => idx !== i));

    return (
        <div className="space-y-3">
            <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
                Drop briefs, designs, brand guides — agents will read these alongside your task descriptions.
            </p>
            <div
                className="rounded-lg p-5 text-center transition-all"
                style={{
                    border: `2px dashed ${drag ? 'var(--accent-primary)' : 'var(--border-subtle)'}`,
                    backgroundColor: drag ? 'var(--accent-subtle)' : 'var(--bg-app)',
                }}
                onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
                onDragLeave={() => setDrag(false)}
                onDrop={(e) => { e.preventDefault(); setDrag(false); filesFromDrop(e.dataTransfer).then(addFiles); }}
            >
                <Upload className="w-6 h-6 mx-auto mb-1.5"
                        style={{ color: drag ? 'var(--accent-primary)' : 'var(--text-tertiary)' }} />
                <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                    Drag files or folders here
                </p>
                <p className="text-xs mt-1" style={{ color: 'var(--text-tertiary)' }}>
                    Both files and folders work when dragged
                </p>
            </div>
            <div className="flex items-center gap-2">
                <button type="button" onClick={() => fileInputRef.current?.click()}
                        className="flex-1 rounded-lg py-2 text-sm font-semibold transition-all"
                        style={{ border: '1px solid var(--border-subtle)', color: 'var(--text-secondary)', backgroundColor: 'var(--bg-app)' }}>
                    Choose files
                </button>
                <button type="button" onClick={() => folderInputRef.current?.click()}
                        className="flex-1 rounded-lg py-2 text-sm font-semibold transition-all"
                        style={{ border: '1px solid var(--border-subtle)', color: 'var(--text-secondary)', backgroundColor: 'var(--bg-app)' }}>
                    Choose a folder
                </button>
            </div>
            <input ref={fileInputRef} type="file" multiple className="hidden"
                   onChange={(e) => { addFiles(e.target.files); e.target.value = ''; }} />
            <input ref={folderInputRef} type="file" webkitdirectory="" directory="" multiple className="hidden"
                   onChange={(e) => { addFiles(e.target.files); e.target.value = ''; }} />
            {files.length > 0 && (
                <div className="space-y-1">
                    {files.map((f, i) => (
                        <div key={f.name + i}
                             className="flex items-center gap-2 px-3 py-1.5 rounded-md text-xs"
                             style={{ backgroundColor: 'var(--bg-panel)', border: '1px solid var(--border-subtle)' }}>
                            <FileText className="w-3.5 h-3.5 flex-shrink-0" style={{ color: 'var(--accent-primary)' }} />
                            <span className="flex-1 truncate" style={{ color: 'var(--text-primary)' }}>{f.relativePath || f.webkitRelativePath || f.name}</span>
                            <span className="flex-shrink-0" style={{ color: 'var(--text-tertiary)' }}>{formatSize(f.size)}</span>
                            <button type="button" onClick={() => remove(i)}
                                    className="p-0.5 rounded-lg hover:bg-red-500/10"
                                    style={{ color: 'var(--text-tertiary)' }}>
                                <Trash2 className="w-3 h-3" />
                            </button>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}


function InitialTasksStep({ tasks, setTasks }) {
    const update = (idx, patch) =>
        setTasks((prev) => prev.map((t, i) => (i === idx ? { ...t, ...patch } : t)));
    const remove = (idx) => setTasks((prev) => prev.filter((_, i) => i !== idx));
    const add = () =>
        setTasks((prev) => [...prev, { title: '', description: '', assignee: '', priority: 'medium' }]);

    return (
        <div className="space-y-3">
            <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
                Tasks the agents pick up the moment the project exists. The description is the
                prompt the assignee reads — leave room for the agent's judgment, don't over-specify.
            </p>
            <div className="space-y-3">
                {tasks.map((t, i) => (
                    <div key={i} className="rounded-lg p-3 space-y-2"
                         style={{ backgroundColor: 'var(--bg-panel)', border: '1px solid var(--border-subtle)' }}>
                        <div className="flex items-center gap-2">
                            <input
                                type="text" value={t.title}
                                onChange={(e) => update(i, { title: e.target.value })}
                                className="input flex-1" placeholder="Task title"
                            />
                            <button type="button" onClick={() => remove(i)}
                                    className="p-1.5 rounded-lg hover:bg-red-500/10"
                                    style={{ color: 'var(--text-tertiary)' }}>
                                <Trash2 className="w-3.5 h-3.5" />
                            </button>
                        </div>
                        <textarea
                            value={t.description}
                            onChange={(e) => update(i, { description: e.target.value })}
                            className="input resize-none h-16 text-xs"
                            placeholder="What should the agent do? (optional — agents can also infer from the project description and attachments)"
                        />
                        <div className="flex gap-2 items-center">
                            <input
                                type="text" value={t.assignee}
                                onChange={(e) => update(i, { assignee: e.target.value })}
                                className="input text-xs flex-1" placeholder="Assignee (agent name, blank = unassigned)"
                            />
                            <select
                                value={t.priority}
                                onChange={(e) => update(i, { priority: e.target.value })}
                                className="input text-xs"
                                style={{ width: 'auto' }}
                            >
                                {PRIORITIES.map((p) => <option key={p} value={p}>{p}</option>)}
                            </select>
                        </div>
                    </div>
                ))}
            </div>
            <button type="button" onClick={add}
                    className="w-full px-3 py-2 rounded-lg flex items-center justify-center gap-1.5 text-xs"
                    style={{
                        border: '1px dashed var(--border-subtle)',
                        color: 'var(--text-secondary)',
                        backgroundColor: 'transparent',
                    }}>
                <Plus className="w-3.5 h-3.5" /> Add task
            </button>
        </div>
    );
}


function AgentsStep({ available, selected, setSelected }) {
    const toggle = (name) => {
        setSelected((prev) => {
            const next = new Set(prev);
            if (next.has(name)) next.delete(name); else next.add(name);
            return next;
        });
    };

    // Conductor first (workspace singleton), then everyone else.
    const ordered = [...available].sort((a, b) => {
        if (a.name === 'Conductor') return -1;
        if (b.name === 'Conductor') return 1;
        return (a.display_name || a.name).localeCompare(b.display_name || b.name);
    });

    return (
        <div className="space-y-3">
            <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
                Which agents are on this project. You can add or remove them later.
                Each agent works from its own system prompt (editable in Forge → Agents).
            </p>
            {ordered.length === 0 && (
                <p className="text-xs italic" style={{ color: 'var(--text-tertiary)' }}>
                    No agents configured yet. You can create them later under Forge → Agents.
                </p>
            )}
            <div className="space-y-1">
                {ordered.map((a) => {
                    const isSel = selected.has(a.name);
                    return (
                        <button key={a.id || a.name} type="button" onClick={() => toggle(a.name)}
                                className="w-full flex items-center gap-3 px-3 py-2 rounded-md text-left transition-colors"
                                style={{
                                    backgroundColor: isSel ? 'var(--accent-subtle)' : 'var(--bg-panel)',
                                    border: `1px solid ${isSel ? 'var(--accent-primary)' : 'var(--border-subtle)'}`,
                                }}>
                            <div className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0"
                                 style={{
                                     backgroundColor: isSel ? 'var(--accent-primary)' : 'var(--bg-app)',
                                     color: isSel ? '#fff' : 'var(--text-secondary)',
                                 }}>
                                {(a.display_name || a.name)[0]?.toUpperCase()}
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="text-sm" style={{ color: 'var(--text-primary)' }}>
                                    {a.display_name || a.name}
                                </div>
                                <div className="text-[10px] truncate" style={{ color: 'var(--text-tertiary)' }}>
                                    {a.name === 'Conductor' ? 'Workspace orchestrator — plans and assigns work' : (a.model || a.name)}
                                </div>
                            </div>
                            {isSel && <Check className="w-4 h-4 flex-shrink-0" style={{ color: 'var(--accent-primary)' }} />}
                        </button>
                    );
                })}
            </div>
        </div>
    );
}


function Label({ children, required }) {
    return (
        <label className="block text-xs font-bold uppercase mb-1.5"
               style={{ color: 'var(--text-tertiary)', letterSpacing: '0.04em' }}>
            {children} {required && <span style={{ color: '#ef4444' }}>*</span>}
        </label>
    );
}
